#!/usr/bin/env python
# coding: utf-8
from __future__ import unicode_literals

import logging
import sys

import dislack


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG, format="%(asctime)s   %(message)s",
                        datefmt='%Y-%m-%d %H:%M:%S')
    sys.exit(0 if dislack.main(sys.argv[1:]) else 1)
